#!/usr/bin/env python3
from pathlib import Path

path = Path('submit.html')
text = path.read_text(encoding='utf-8')
old = """  function buildGitHubIssueBody() {\n    const payload = getSubmissionPayload();\n    if (!payload) return '';\n    const bytes = new TextEncoder().encode(JSON.stringify(payload));\n    let binary = ''; bytes.forEach(byte => binary += String.fromCharCode(byte));\n    const encoded = btoa(binary).replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=+$/g, '');\n    return '<!-- OPERATIONAL-AREA-SUBMISSION -->\\n\\n<!-- Submission details are populated automatically by the Operational Area Submission Tool. -->\\n\\n<!-- OAM2:' + encoded + ' -->';\n  }"""
new = """  function buildGitHubIssueBody() {\n    const payload = getSubmissionPayload();\n    if (!payload) return '';\n    const bytes = new TextEncoder().encode(JSON.stringify(payload));\n    let binary = ''; bytes.forEach(byte => binary += String.fromCharCode(byte));\n    const encoded = btoa(binary).replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=+$/g, '');\n    const definition = payload.operational_area_definition;\n    let definitionText = '';\n    if (definition && definition.type === 'MultiCircle') {\n      definitionText = '**Geometry Type:** MultiCircle\\n\\n' + definition.circles.map((c, i) => {\n        const p = c.center_point;\n        return '**Circle ' + (i + 1) + ':** ' + p.latitude + ', ' + p.longitude + ' — ' + (Number(c.radius_meters) / 1609.344).toFixed(2) + ' mi (' + (Number(c.radius_meters) / 1000).toFixed(2) + ' km)';\n      }).join('\\n');\n    } else {\n      const geometryType = payload.geometry && payload.geometry.type ? payload.geometry.type : (definition && definition.type ? definition.type : 'Unknown');\n      definitionText = '**Geometry Type:** ' + geometryType;\n      if (definition && definition.type === 'Circle') {\n        definitionText += '\\n\\n**Center:** ' + definition.center_point.latitude + ', ' + definition.center_point.longitude + '\\n**Radius:** ' + (Number(definition.radius_meters) / 1609.344).toFixed(2) + ' mi (' + (Number(definition.radius_meters) / 1000).toFixed(2) + ' km)';\n      }\n    }\n    return '<!-- OPERATIONAL-AREA-SUBMISSION -->\\n\\n## Operational Area Submission\\n\\n' +\n      '**Operator ID:** ' + payload.operator_id + '\\n\\n' +\n      '**Site / Area ID:** ' + payload.site_id + '\\n\\n' +\n      '**Metro / Locality:** ' + payload.metro_locality + '\\n\\n' +\n      '**Effective From:** ' + (payload.effective_from || 'Not specified') + '\\n\\n' +\n      '**Effective To:** ' + (payload.effective_to || 'Not specified') + '\\n\\n' +\n      '### Operational Area Definition\\n\\n' + definitionText + '\\n\\n' +\n      '<!-- OAM2:' + encoded + ' -->';\n  }"""
if old not in text:
    raise SystemExit('target buildGitHubIssueBody function not found')
path.write_text(text.replace(old, new), encoding='utf-8')
print('patched', path)
